/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.controllers.GestorConsultas;
import negocio.entities.Usuario;
import net.ucanaccess.util.Logger;

/**
 *
 * @author david
 */
public class PantallaJefeGabineteVicerrectorado extends javax.swing.JFrame {

	private Usuario usuario;

	/**
	 * Creates new form PantallaJefeGabineteVicerrectorado
	 * @throws Exception 
	 */
	public PantallaJefeGabineteVicerrectorado(Usuario usuario) throws Exception {
		this.usuario = usuario;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws Exception 
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws Exception {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		this.jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Usuario: " + usuario.getDNI());

		jButton1.setText("Conocer ingresos");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					Logger.log("mensaje de error");
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(jLabel2).addComponent(jButton1)
								.addComponent(jLabel3).addComponent(jLabel4).addComponent(jLabel5))
						.addContainerGap(219, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jButton1).addGap(18, 18, 18).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel5)
						.addContainerGap(108, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {// GEN-FIRST:event_jButton1ActionPerformed
		String[] ingresos = GestorConsultas.obtenerIngresos();
		int sum = Integer.parseInt(ingresos[0]) + Integer.parseInt(ingresos[1]) + Integer.parseInt(ingresos[2]);

		jLabel2.setText("Enseñanzas sin titulación: " + ingresos[0] + "€");

		jLabel3.setText("Enseñanzas con titulación:" + ingresos[1] + "€");

		jLabel4.setText("Enseñanzas propias:" + ingresos[2] + "€");

		jLabel5.setText("Total: " + sum + "€");


	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables
}
