/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.controllers.GestorConsultas;
import negocio.entities.Usuario;
import java.awt.event.*;

/**
 *
 * @author david
 * 
 * NOTA:
 * Cada vez que se edita la interfaz se sobreescribe todo de initComponets(), y pierdes tu codigo
 * Hay que añadir al final, antes de la llamada a pack(), y llamar a la funcion buttons(), para que los botones funcionen
 * 
 * Tambien, en la label lblUser, hay que poner en el setText(), la variable "String u"
 */
public class PantallaJefeGabineteVicerrectorado extends javax.swing.JFrame {

	/**
	 * Creates new form PantallaJefeGabineteVicerrectorado
	 */
	Usuario user;
	String u;
	public PantallaJefeGabineteVicerrectorado(Usuario user) {
		this.user = user;
		u = "Usuario: " + user.getDNI();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListarEdiciones = new javax.swing.JFrame();
        consultarCursos = new javax.swing.JFrame();
        ConsultarIngresos = new javax.swing.JFrame();
        lblUserIngresos = new javax.swing.JLabel();
        lblSinTit = new javax.swing.JLabel();
        labelConTit = new javax.swing.JLabel();
        lblEnsProp = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnConsultarIngresos = new javax.swing.JButton();
        btnListarEdiciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        ListarEdiciones.setAutoRequestFocus(false);
        ListarEdiciones.setSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout ListarEdicionesLayout = new javax.swing.GroupLayout(ListarEdiciones.getContentPane());
        ListarEdiciones.getContentPane().setLayout(ListarEdicionesLayout);
        ListarEdicionesLayout.setHorizontalGroup(
            ListarEdicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ListarEdicionesLayout.setVerticalGroup(
            ListarEdicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        consultarCursos.setSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout consultarCursosLayout = new javax.swing.GroupLayout(consultarCursos.getContentPane());
        consultarCursos.getContentPane().setLayout(consultarCursosLayout);
        consultarCursosLayout.setHorizontalGroup(
            consultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        consultarCursosLayout.setVerticalGroup(
            consultarCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ConsultarIngresos.setSize(new java.awt.Dimension(400, 400));

        lblUserIngresos.setText("Usuario: ");

        javax.swing.GroupLayout ConsultarIngresosLayout = new javax.swing.GroupLayout(ConsultarIngresos.getContentPane());
        ConsultarIngresos.getContentPane().setLayout(ConsultarIngresosLayout);
        ConsultarIngresosLayout.setHorizontalGroup(
            ConsultarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserIngresos)
                    .addComponent(lblSinTit)
                    .addComponent(labelConTit)
                    .addComponent(lblEnsProp)
                    .addComponent(lblTotal))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        ConsultarIngresosLayout.setVerticalGroup(
            ConsultarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserIngresos)
                .addGap(30, 30, 30)
                .addComponent(lblSinTit)
                .addGap(18, 18, 18)
                .addComponent(labelConTit)
                .addGap(18, 18, 18)
                .addComponent(lblEnsProp)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(400, 400));

        lblUser.setText(u);

        btnConsultarIngresos.setText("Consultar Ingresos");

        btnListarEdiciones.setText("Listar Ediciones");

        jButton1.setText("Consultar cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultarIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarEdiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarIngresos)
                .addGap(27, 27, 27)
                .addComponent(btnListarEdiciones)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        buttons();
        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void buttons() {
		btnConsultarIngresos.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				ConsultarIngresos.setVisible(true);
				lblUser.setText(u);
				String[] ingresos;
				try {
					ingresos = GestorConsultas.obtenerIngresos();
					int sum = Integer.parseInt(ingresos[0]) + Integer.parseInt(ingresos[1])
							+ Integer.parseInt(ingresos[2]);

					lblSinTit.setText("Enseñanzas sin titulación: " + ingresos[0] + "€");

					labelConTit.setText("Enseñanzas con titulación:" + ingresos[1] + "€");

					lblEnsProp.setText("Enseñanzas propias:" + ingresos[2] + "€");

					lblTotal.setText("Total: " + sum + "€");
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}
		});
	}

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ConsultarIngresos;
    private javax.swing.JFrame ListarEdiciones;
    private javax.swing.JButton btnConsultarIngresos;
    private javax.swing.JButton btnListarEdiciones;
    private javax.swing.JFrame consultarCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelConTit;
    private javax.swing.JLabel lblEnsProp;
    private javax.swing.JLabel lblSinTit;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserIngresos;
    // End of variables declaration//GEN-END:variables
}
